name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: build & test
      run: |
        yarn,
        yarn build,
        yarn test
